import { execFileSync } from 'node:child_process';
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import {
  EnvironmentError,
  MEMORY_CLASS_DIRECTORIES,
  UserError,
  memoryPath,
  serializeMemoryFile,
  type Memory,
} from '@teambrain/core';

// M2.3: writes the imported brain onto branch `teambrain/init` through a
// temporary git worktree. The user's checkout is never switched, staged,
// or dirtied — main stays untouched by construction (principle 4: no
// code path writes memories to main; automation writes to branches).

export const INIT_BRANCH = 'teambrain/init';

export interface InitBranchResult {
  branch: string;
  commit: string;
  fileCount: number;
  /** Ref the branch was created from: main, master, or HEAD. */
  base: string;
}

function git(args: string[], cwd: string): string {
  try {
    return execFileSync('git', args, {
      cwd,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'pipe'],
    }).trim();
  } catch (err) {
    const stderr = (err as { stderr?: string }).stderr ?? '';
    throw new EnvironmentError(
      `git ${args.join(' ')} failed: ${stderr.trim() || (err as Error).message}`,
      { cause: err },
    );
  }
}

function tryGit(args: string[], cwd: string): string | null {
  try {
    return git(args, cwd);
  } catch {
    return null;
  }
}

const DEFAULT_BRAIN_YAML = `version: 1
capture:
  level: metadata
redaction:
  level: strict
required_tags: []
`;

function renderIndex(memories: Memory[], createdDate: string): string {
  let index = `# TeamBrain memory index\n\nGenerated by \`tb init\` on ${createdDate}. ${memories.length} memories.\n`;
  for (const classDir of Object.values(MEMORY_CLASS_DIRECTORIES)) {
    const ofClass = memories.filter(
      (memory) => MEMORY_CLASS_DIRECTORIES[memory.class] === classDir,
    );
    if (ofClass.length === 0) continue;
    index += `\n## ${classDir}\n\n`;
    for (const memory of ofClass) {
      const source =
        memory.tags
          .find((tag) => tag.startsWith('source:'))
          ?.slice('source:'.length) ?? 'unknown';
      index += `- ${memory.id} — "${memory.title}" (source: ${source})\n`;
    }
  }
  return index;
}

// Without this, autocrlf machines check the brain out with CRLF and the
// byte-exact parser (and therefore tb lint) rejects every memory file.
const BRAIN_GITATTRIBUTES = `# Memory files are parsed byte-exactly (LF-only).
* text eol=lf
`;

/** Writes the C7 brain layout into `brainDir` (creating it). */
function writeBrainTree(brainDir: string, memories: Memory[]): number {
  mkdirSync(brainDir, { recursive: true });
  writeFileSync(join(brainDir, '.gitattributes'), BRAIN_GITATTRIBUTES, 'utf8');
  writeFileSync(join(brainDir, 'brain.yaml'), DEFAULT_BRAIN_YAML, 'utf8');
  for (const memory of memories) {
    const relativePath = memoryPath(memory);
    const absolutePath = join(brainDir, relativePath);
    mkdirSync(dirname(absolutePath), { recursive: true });
    writeFileSync(absolutePath, serializeMemoryFile(memory), 'utf8');
  }
  const createdDate = memories[0]?.created ?? 'unknown date';
  writeFileSync(
    join(brainDir, 'INDEX.md'),
    renderIndex(memories, createdDate),
    'utf8',
  );
  return memories.length + 3; // memories + .gitattributes + brain.yaml + INDEX.md
}

/**
 * Preflight for `tb init`: validates the target and resolves it to the
 * repository toplevel (a subdirectory target would otherwise scan the
 * subdir but write the brain at the root). Exported so the command can
 * run it before doing any work — a non-git target should say so, not
 * "nothing to import". Returns the repo root all further work uses.
 */
export function validateInitTarget(repoDir: string): string {
  if (tryGit(['rev-parse', '--is-inside-work-tree'], repoDir) !== 'true') {
    throw new UserError(
      `${repoDir} is not a git repository — run tb init inside the repo the brain should live in`,
    );
  }
  const repoRoot = git(['rev-parse', '--show-toplevel'], repoDir);
  if (tryGit(['rev-parse', '--verify', 'HEAD'], repoRoot) === null) {
    throw new UserError(
      'the repository has no commits yet — make an initial commit first',
    );
  }
  if (existsSync(join(repoRoot, '.teambrain'))) {
    throw new UserError(
      '.teambrain already exists in this repository — it looks initialized',
    );
  }
  if (
    tryGit(['rev-parse', '--verify', `refs/heads/${INIT_BRANCH}`], repoRoot) !==
    null
  ) {
    throw new UserError(
      `branch ${INIT_BRANCH} already exists — merge or delete it before re-running tb init`,
    );
  }
  return repoRoot;
}

/**
 * The init branch parents on the default branch when one exists, so a
 * later PR to main carries only the brain — not whatever feature branch
 * the user happened to be standing on.
 */
function resolveBaseRef(repoRoot: string): string {
  for (const branch of ['main', 'master']) {
    if (
      tryGit(['rev-parse', '--verify', `refs/heads/${branch}`], repoRoot) !==
      null
    ) {
      return branch;
    }
  }
  return 'HEAD';
}

export function writeInitBranch(
  repoDir: string,
  memories: Memory[],
): InitBranchResult {
  const repoRoot = validateInitTarget(repoDir);
  const base = resolveBaseRef(repoRoot);

  const scratchRoot = mkdtempSync(join(tmpdir(), 'teambrain-init-'));
  const worktreeDir = join(scratchRoot, 'worktree');
  let branchCreated = false;
  try {
    git(['worktree', 'add', worktreeDir, '-b', INIT_BRANCH, base], repoRoot);
    branchCreated = true;

    const fileCount = writeBrainTree(join(worktreeDir, '.teambrain'), memories);
    git(['add', '.teambrain'], worktreeDir);
    git(
      [
        'commit',
        '-m',
        `chore(teambrain): import ${memories.length} memories via tb init`,
      ],
      worktreeDir,
    );
    const commit = git(['rev-parse', 'HEAD'], worktreeDir);
    return { branch: INIT_BRANCH, commit, fileCount, base };
  } catch (err) {
    // Leave the repo exactly as found: drop the half-made branch.
    if (branchCreated) {
      tryGit(['worktree', 'remove', '--force', worktreeDir], repoRoot);
      tryGit(['branch', '-D', INIT_BRANCH], repoRoot);
    }
    throw err;
  } finally {
    tryGit(['worktree', 'remove', '--force', worktreeDir], repoRoot);
    tryGit(['worktree', 'prune'], repoRoot);
    rmSync(scratchRoot, { recursive: true, force: true });
  }
}
