#!/usr/bin/env node
// Regenerates the README test-count claim from a real vitest run.
//
// R3b (field report 001): the public copy said "500+ tests" while the suite had
// 715. Undercounting is the harmless direction, but a hand-typed number in a
// project whose thesis is verifiable claims is the wrong artifact. No number in
// public copy that a machine cannot regenerate.
//
//   node scripts/claims.mjs            rewrite the README region
//   node scripts/claims.mjs --check    exit 1 if the region is stale (CI gate)
//
// This is a down payment on `tb verify` (E-series): same idea, narrower scope.
import { spawnSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const START = '<!-- claims:tests:start -->';
const END = '<!-- claims:tests:end -->';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const check = process.argv.includes('--check');

/** Runs the suite and reads the counts back out of vitest's JSON report. */
function measure() {
  // The JSON reporter shares stdout with vitest's own chatter, so route the
  // report through a file rather than parsing stdout.
  const dir = mkdtempSync(join(tmpdir(), 'tb-claims-'));
  const reportPath = join(dir, 'report.json');
  try {
    const result = spawnSync(
      process.execPath,
      [
        join(root, 'node_modules', 'vitest', 'vitest.mjs'),
        'run',
        '--reporter=json',
        `--outputFile=${reportPath}`,
      ],
      { cwd: root, stdio: ['ignore', 'ignore', 'pipe'], encoding: 'utf8' },
    );

    let report;
    try {
      report = JSON.parse(readFileSync(reportPath, 'utf8'));
    } catch {
      // The suite's integration tests are chatty on stderr even when green, so
      // it is only worth surfacing when there is no report to read.
      process.stderr.write(result.stderr ?? '');
      throw new Error(
        `vitest exited ${result.status ?? 'on signal ' + result.signal} ` +
          'without writing a report — claims need a green suite',
      );
    }

    const failedFiles = report.testResults.filter((f) => f.status !== 'passed');
    if (report.numFailedTests > 0 || failedFiles.length > 0) {
      for (const file of failedFiles) console.error(`  failed: ${file.name}`);
      throw new Error(
        `${report.numFailedTests} failing test(s) — ` +
          'claims are only regenerated from a green suite',
      );
    }

    // A non-zero exit with a fully green report means vitest hit an unhandled
    // error outside the tests — on slow filesystems the worker RPC can time out
    // ("Timeout calling onTaskUpdate") while every file still passes. That does
    // not invalidate the counts, but it is worth saying out loud rather than
    // swallowing.
    if (result.status !== 0) {
      console.warn(
        `claims: vitest exited ${result.status} with every test passing ` +
          '(unhandled error outside the tests); counts below are still valid',
      );
    }

    return {
      // numTotalTestSuites counts describe blocks (256), not files. The file
      // count the copy actually claims is the length of testResults.
      tests: report.numTotalTests,
      files: report.testResults.length,
    };
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

function renderRegion({ tests, files }, version) {
  return [
    START,
    `**${tests} tests across ${files} test files**, all green on ` +
      `\`@teambrain/cli@${version}\`. This line is generated by ` +
      '`scripts/claims.mjs` from a real `vitest run`, and CI fails if it ' +
      'drifts from the suite.',
    END,
  ].join('\n');
}

const readmePath = join(root, 'README.md');
const readme = readFileSync(readmePath, 'utf8');

const start = readme.indexOf(START);
const end = readme.indexOf(END);
if (start === -1 || end === -1 || end < start) {
  console.error(`claims: README.md is missing the ${START} / ${END} markers`);
  process.exit(1);
}

const version = JSON.parse(
  readFileSync(join(root, 'packages', 'cli', 'package.json'), 'utf8'),
).version;

const next = renderRegion(measure(), version);
const current = readme.slice(start, end + END.length);

if (current === next) {
  console.log('claims: README test counts are up to date');
  process.exit(0);
}

if (check) {
  console.error('claims: README test counts are stale.');
  console.error('--- README has ---');
  console.error(current);
  console.error('--- measured ---');
  console.error(next);
  console.error('Run `node scripts/claims.mjs` and commit the result.');
  process.exit(1);
}

writeFileSync(
  readmePath,
  readme.slice(0, start) + next + readme.slice(end + END.length),
);
console.log('claims: rewrote the README test-count region');
